all: test1 test2 test3 test4 test5 test6 test7 test8 test9

test1: test1.c
	gcc -o test1 test1.c
test2: test2.c
	gcc -o test2 test2.c
test3: test3.c
	gcc -o test3 test3.c	
test4: test4.c
	gcc -o test4 test4.c	
test5: test5.c
	gcc -o test5 test5.c
test6: test6.c
	gcc -o test6 test6.c

test7: test7.c
	gcc -o test7 test7.c

test8: test8.c
	gcc -o test8 test8.c

test9: test9.c
	gcc -o test9 test9.c

clean:
	$(RM) test1 test2 test3 test4 test5 test6 test7 test8 test9